spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          naver:
            client-id:
            client-secret:
            redirect-uri:
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
        provider: # naver ??? ??
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response